### ISSUE TITLE
High CPU Usage by CAdvisor

### ISSUE THREAD

**Issue by micalm** [Drakonis96/dockerstats#1]
Stable ~10% on i5-8400 (6x2.8-4.0GHz) on default configuration, which I think is irreasonably high.

Tracked here on upstream: https://github.com/google/cadvisor/issues/2523

I confirmed that the suggested (hot)fix for this is working (drops to =< 1%) and doesn't seem to impact docker-stats functionality. Modified the docker-compose like so:

```
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080" # You can change the external port if you wish
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ### NEW
    command:
      - --docker_only=true
      - --housekeeping_interval=10s
    ### END NEW
    restart: unless-stopped
    privileged: true
```

Not creating this as a PR yet, as there are further suggested optimizations to the CAdvisor image regarding `--disable_metrics=`. I didn't dig deep enough in neither project to know what is or isn't applicable here, but maybe the author or someone else will have the knowledge or time to check this.
